/* Overlap — cities.js
 * ~330 major cities → IANA time zones. Fields:
 *   n: English name   c: country   z: IANA zone   h: 中文名   a: aliases (romanizations, abbreviations, 中文别名)
 * Zone rules: always a real IANA ID (never a fixed offset). Mainland China cities all map to
 * Asia/Shanghai (official national time). Ids are generated below (slug of name, +country on collision).
 */
(function () {
  "use strict";
  var C = [
    /* -------- United States -------- */
    { n: "New York", c: "United States", z: "America/New_York", h: "纽约", a: ["NYC", "New York City", "纽约市"] },
    { n: "Los Angeles", c: "United States", z: "America/Los_Angeles", h: "洛杉矶", a: ["LA"] },
    { n: "Chicago", c: "United States", z: "America/Chicago", h: "芝加哥" },
    { n: "Houston", c: "United States", z: "America/Chicago", h: "休斯敦", a: ["休斯顿"] },
    { n: "Phoenix", c: "United States", z: "America/Phoenix", h: "菲尼克斯", a: ["凤凰城"] },
    { n: "Philadelphia", c: "United States", z: "America/New_York", h: "费城", a: ["Philly"] },
    { n: "San Antonio", c: "United States", z: "America/Chicago", h: "圣安东尼奥" },
    { n: "San Diego", c: "United States", z: "America/Los_Angeles", h: "圣地亚哥", a: ["圣迭戈"] },
    { n: "Dallas", c: "United States", z: "America/Chicago", h: "达拉斯" },
    { n: "Austin", c: "United States", z: "America/Chicago", h: "奥斯汀" },
    { n: "San Jose", c: "United States", z: "America/Los_Angeles", h: "圣何塞", a: ["Silicon Valley", "硅谷"] },
    { n: "San Francisco", c: "United States", z: "America/Los_Angeles", h: "旧金山", a: ["SF", "三藩市", "圣弗朗西斯科"] },
    { n: "Seattle", c: "United States", z: "America/Los_Angeles", h: "西雅图" },
    { n: "Denver", c: "United States", z: "America/Denver", h: "丹佛" },
    { n: "Boston", c: "United States", z: "America/New_York", h: "波士顿" },
    { n: "Washington", c: "United States", z: "America/New_York", h: "华盛顿", a: ["DC", "Washington DC", "华盛顿特区"] },
    { n: "Miami", c: "United States", z: "America/New_York", h: "迈阿密" },
    { n: "Atlanta", c: "United States", z: "America/New_York", h: "亚特兰大" },
    { n: "New Orleans", c: "United States", z: "America/Chicago", h: "新奥尔良" },
    { n: "Las Vegas", c: "United States", z: "America/Los_Angeles", h: "拉斯维加斯", a: ["Vegas"] },
    { n: "Portland", c: "United States", z: "America/Los_Angeles", h: "波特兰" },
    { n: "Minneapolis", c: "United States", z: "America/Chicago", h: "明尼阿波利斯", a: ["Twin Cities", "双子城"] },
    { n: "Detroit", c: "United States", z: "America/Detroit", h: "底特律" },
    { n: "Salt Lake City", c: "United States", z: "America/Denver", h: "盐湖城", a: ["SLC"] },
    { n: "Charlotte", c: "United States", z: "America/New_York", h: "夏洛特" },
    { n: "Nashville", c: "United States", z: "America/Chicago", h: "纳什维尔" },
    { n: "Kansas City", c: "United States", z: "America/Chicago", h: "堪萨斯城" },
    { n: "St. Louis", c: "United States", z: "America/Chicago", h: "圣路易斯", a: ["Saint Louis"] },
    { n: "Pittsburgh", c: "United States", z: "America/New_York", h: "匹兹堡" },
    { n: "Cincinnati", c: "United States", z: "America/New_York", h: "辛辛那提" },
    { n: "Cleveland", c: "United States", z: "America/New_York", h: "克利夫兰" },
    { n: "Orlando", c: "United States", z: "America/New_York", h: "奥兰多" },
    { n: "Tampa", c: "United States", z: "America/New_York", h: "坦帕" },
    { n: "Baltimore", c: "United States", z: "America/New_York", h: "巴尔的摩" },
    { n: "Sacramento", c: "United States", z: "America/Los_Angeles", h: "萨克拉门托" },
    { n: "Anchorage", c: "United States", z: "America/Anchorage", h: "安克雷奇", a: ["Alaska", "阿拉斯加"] },
    { n: "Honolulu", c: "United States", z: "Pacific/Honolulu", h: "檀香山", a: ["Hawaii", "火奴鲁鲁", "夏威夷"] },
    { n: "Columbus", c: "United States", z: "America/New_York", h: "哥伦布" },
    { n: "Indianapolis", c: "United States", z: "America/Indiana/Indianapolis", h: "印第安纳波利斯", a: ["Indy"] },
    { n: "Milwaukee", c: "United States", z: "America/Chicago", h: "密尔沃基" },
    { n: "Raleigh", c: "United States", z: "America/New_York", h: "罗利" },
    { n: "Albuquerque", c: "United States", z: "America/Denver", h: "阿尔伯克基" },
    { n: "El Paso", c: "United States", z: "America/Denver", h: "埃尔帕索" },
    { n: "Boise", c: "United States", z: "America/Boise", h: "博伊西" },
    { n: "Omaha", c: "United States", z: "America/Chicago", h: "奥马哈" },
    { n: "Oklahoma City", c: "United States", z: "America/Chicago", h: "俄克拉何马城" },
    { n: "Memphis", c: "United States", z: "America/Chicago", h: "孟菲斯" },
    { n: "Louisville", c: "United States", z: "America/Kentucky/Louisville", h: "路易维尔" },
    { n: "Buffalo", c: "United States", z: "America/New_York", h: "布法罗", a: ["水牛城"] },
    { n: "Hartford", c: "United States", z: "America/New_York", h: "哈特福德" },
    /* -------- Canada -------- */
    { n: "Toronto", c: "Canada", z: "America/Toronto", h: "多伦多" },
    { n: "Vancouver", c: "Canada", z: "America/Vancouver", h: "温哥华" },
    { n: "Montreal", c: "Canada", z: "America/Toronto", h: "蒙特利尔", a: ["Montréal", "满地可"] },
    { n: "Calgary", c: "Canada", z: "America/Edmonton", h: "卡尔加里" },
    { n: "Edmonton", c: "Canada", z: "America/Edmonton", h: "埃德蒙顿" },
    { n: "Ottawa", c: "Canada", z: "America/Toronto", h: "渥太华" },
    { n: "Winnipeg", c: "Canada", z: "America/Winnipeg", h: "温尼伯" },
    { n: "Quebec City", c: "Canada", z: "America/Toronto", h: "魁北克城", a: ["Québec"] },
    { n: "Halifax", c: "Canada", z: "America/Halifax", h: "哈利法克斯" },
    { n: "St. John's", c: "Canada", z: "America/St_Johns", h: "圣约翰斯" },
    { n: "Victoria", c: "Canada", z: "America/Vancouver", h: "维多利亚" },
    { n: "Regina", c: "Canada", z: "America/Regina", h: "里贾纳" },
    /* -------- Mexico & Central America -------- */
    { n: "Mexico City", c: "Mexico", z: "America/Mexico_City", h: "墨西哥城", a: ["CDMX", "Ciudad de México"] },
    { n: "Guadalajara", c: "Mexico", z: "America/Mexico_City", h: "瓜达拉哈拉" },
    { n: "Monterrey", c: "Mexico", z: "America/Monterrey", h: "蒙特雷" },
    { n: "Tijuana", c: "Mexico", z: "America/Tijuana", h: "蒂华纳" },
    { n: "Cancun", c: "Mexico", z: "America/Cancun", h: "坎昆", a: ["Cancún"] },
    { n: "Puebla", c: "Mexico", z: "America/Mexico_City", h: "普埃布拉" },
    { n: "Guatemala City", c: "Guatemala", z: "America/Guatemala", h: "危地马拉城" },
    { n: "San Salvador", c: "El Salvador", z: "America/El_Salvador", h: "圣萨尔瓦多" },
    { n: "Tegucigalpa", c: "Honduras", z: "America/Tegucigalpa", h: "特古西加尔巴" },
    { n: "Managua", c: "Nicaragua", z: "America/Managua", h: "马那瓜" },
    { n: "San Jose", c: "Costa Rica", z: "America/Costa_Rica", h: "圣何塞", a: ["San José"] },
    { n: "Panama City", c: "Panama", z: "America/Panama", h: "巴拿马城" },
    /* -------- Caribbean -------- */
    { n: "Havana", c: "Cuba", z: "America/Havana", h: "哈瓦那", a: ["La Habana"] },
    { n: "Santo Domingo", c: "Dominican Republic", z: "America/Santo_Domingo", h: "圣多明各" },
    { n: "San Juan", c: "Puerto Rico", z: "America/Puerto_Rico", h: "圣胡安" },
    { n: "Kingston", c: "Jamaica", z: "America/Jamaica", h: "金斯敦" },
    { n: "Port-au-Prince", c: "Haiti", z: "America/Port-au-Prince", h: "太子港" },
    { n: "Nassau", c: "Bahamas", z: "America/Nassau", h: "拿骚" },
    /* -------- South America -------- */
    { n: "Sao Paulo", c: "Brazil", z: "America/Sao_Paulo", h: "圣保罗", a: ["São Paulo"] },
    { n: "Rio de Janeiro", c: "Brazil", z: "America/Sao_Paulo", h: "里约热内卢", a: ["Rio", "里约"] },
    { n: "Brasilia", c: "Brazil", z: "America/Sao_Paulo", h: "巴西利亚", a: ["Brasília"] },
    { n: "Salvador", c: "Brazil", z: "America/Bahia", h: "萨尔瓦多" },
    { n: "Fortaleza", c: "Brazil", z: "America/Fortaleza", h: "福塔莱萨" },
    { n: "Recife", c: "Brazil", z: "America/Recife", h: "累西腓" },
    { n: "Manaus", c: "Brazil", z: "America/Manaus", h: "马瑙斯" },
    { n: "Porto Alegre", c: "Brazil", z: "America/Sao_Paulo", h: "阿雷格里港" },
    { n: "Buenos Aires", c: "Argentina", z: "America/Argentina/Buenos_Aires", h: "布宜诺斯艾利斯" },
    { n: "Cordoba", c: "Argentina", z: "America/Argentina/Cordoba", h: "科尔多瓦", a: ["Córdoba"] },
    { n: "Santiago", c: "Chile", z: "America/Santiago", h: "圣地亚哥" },
    { n: "Lima", c: "Peru", z: "America/Lima", h: "利马" },
    { n: "Bogota", c: "Colombia", z: "America/Bogota", h: "波哥大", a: ["Bogotá"] },
    { n: "Medellin", c: "Colombia", z: "America/Bogota", h: "麦德林", a: ["Medellín"] },
    { n: "Cali", c: "Colombia", z: "America/Bogota", h: "卡利" },
    { n: "Caracas", c: "Venezuela", z: "America/Caracas", h: "加拉加斯" },
    { n: "Quito", c: "Ecuador", z: "America/Guayaquil", h: "基多" },
    { n: "Guayaquil", c: "Ecuador", z: "America/Guayaquil", h: "瓜亚基尔" },
    { n: "La Paz", c: "Bolivia", z: "America/La_Paz", h: "拉巴斯" },
    { n: "Montevideo", c: "Uruguay", z: "America/Montevideo", h: "蒙得维的亚" },
    { n: "Asuncion", c: "Paraguay", z: "America/Asuncion", h: "亚松森", a: ["Asunción"] },
    /* -------- Europe: UK & Ireland -------- */
    { n: "London", c: "United Kingdom", z: "Europe/London", h: "伦敦" },
    { n: "Manchester", c: "United Kingdom", z: "Europe/London", h: "曼彻斯特", a: ["曼城"] },
    { n: "Birmingham", c: "United Kingdom", z: "Europe/London", h: "伯明翰" },
    { n: "Edinburgh", c: "United Kingdom", z: "Europe/London", h: "爱丁堡" },
    { n: "Glasgow", c: "United Kingdom", z: "Europe/London", h: "格拉斯哥" },
    { n: "Dublin", c: "Ireland", z: "Europe/Dublin", h: "都柏林" },
    /* -------- Europe: France -------- */
    { n: "Paris", c: "France", z: "Europe/Paris", h: "巴黎" },
    { n: "Lyon", c: "France", z: "Europe/Paris", h: "里昂" },
    { n: "Marseille", c: "France", z: "Europe/Paris", h: "马赛" },
    { n: "Nice", c: "France", z: "Europe/Paris", h: "尼斯" },
    /* -------- Europe: Germany -------- */
    { n: "Berlin", c: "Germany", z: "Europe/Berlin", h: "柏林" },
    { n: "Munich", c: "Germany", z: "Europe/Berlin", h: "慕尼黑", a: ["München"] },
    { n: "Hamburg", c: "Germany", z: "Europe/Berlin", h: "汉堡" },
    { n: "Frankfurt", c: "Germany", z: "Europe/Berlin", h: "法兰克福" },
    { n: "Cologne", c: "Germany", z: "Europe/Berlin", h: "科隆", a: ["Köln"] },
    { n: "Stuttgart", c: "Germany", z: "Europe/Berlin", h: "斯图加特" },
    { n: "Dusseldorf", c: "Germany", z: "Europe/Berlin", h: "杜塞尔多夫", a: ["Düsseldorf"] },
    /* -------- Europe: Iberia -------- */
    { n: "Madrid", c: "Spain", z: "Europe/Madrid", h: "马德里" },
    { n: "Barcelona", c: "Spain", z: "Europe/Madrid", h: "巴塞罗那", a: ["巴萨"] },
    { n: "Valencia", c: "Spain", z: "Europe/Madrid", h: "瓦伦西亚", a: ["巴伦西亚"] },
    { n: "Seville", c: "Spain", z: "Europe/Madrid", h: "塞维利亚", a: ["Sevilla"] },
    { n: "Lisbon", c: "Portugal", z: "Europe/Lisbon", h: "里斯本", a: ["Lisboa"] },
    { n: "Porto", c: "Portugal", z: "Europe/Lisbon", h: "波尔图" },
    /* -------- Europe: Italy -------- */
    { n: "Rome", c: "Italy", z: "Europe/Rome", h: "罗马", a: ["Roma"] },
    { n: "Milan", c: "Italy", z: "Europe/Rome", h: "米兰", a: ["Milano"] },
    { n: "Naples", c: "Italy", z: "Europe/Rome", h: "那不勒斯", a: ["Napoli", "那波利"] },
    { n: "Turin", c: "Italy", z: "Europe/Rome", h: "都灵", a: ["Torino"] },
    { n: "Florence", c: "Italy", z: "Europe/Rome", h: "佛罗伦萨", a: ["Firenze", "翡冷翠"] },
    { n: "Venice", c: "Italy", z: "Europe/Rome", h: "威尼斯", a: ["Venezia"] },
    /* -------- Europe: Benelux -------- */
    { n: "Amsterdam", c: "Netherlands", z: "Europe/Amsterdam", h: "阿姆斯特丹" },
    { n: "Rotterdam", c: "Netherlands", z: "Europe/Amsterdam", h: "鹿特丹" },
    { n: "The Hague", c: "Netherlands", z: "Europe/Amsterdam", h: "海牙", a: ["Den Haag"] },
    { n: "Brussels", c: "Belgium", z: "Europe/Brussels", h: "布鲁塞尔", a: ["Bruxelles"] },
    { n: "Antwerp", c: "Belgium", z: "Europe/Brussels", h: "安特卫普", a: ["Antwerpen"] },
    { n: "Luxembourg", c: "Luxembourg", z: "Europe/Luxembourg", h: "卢森堡" },
    /* -------- Europe: Alpine -------- */
    { n: "Vienna", c: "Austria", z: "Europe/Vienna", h: "维也纳", a: ["Wien"] },
    { n: "Zurich", c: "Switzerland", z: "Europe/Zurich", h: "苏黎世", a: ["Zürich"] },
    { n: "Geneva", c: "Switzerland", z: "Europe/Zurich", h: "日内瓦", a: ["Genève"] },
    { n: "Basel", c: "Switzerland", z: "Europe/Zurich", h: "巴塞尔" },
    { n: "Bern", c: "Switzerland", z: "Europe/Zurich", h: "伯尔尼" },
    /* -------- Europe: Nordics -------- */
    { n: "Stockholm", c: "Sweden", z: "Europe/Stockholm", h: "斯德哥尔摩" },
    { n: "Gothenburg", c: "Sweden", z: "Europe/Stockholm", h: "哥德堡", a: ["Göteborg"] },
    { n: "Oslo", c: "Norway", z: "Europe/Oslo", h: "奥斯陆" },
    { n: "Copenhagen", c: "Denmark", z: "Europe/Copenhagen", h: "哥本哈根", a: ["København"] },
    { n: "Helsinki", c: "Finland", z: "Europe/Helsinki", h: "赫尔辛基" },
    { n: "Reykjavik", c: "Iceland", z: "Atlantic/Reykjavik", h: "雷克雅未克", a: ["Reykjavík"] },
    /* -------- Europe: Central & Eastern -------- */
    { n: "Warsaw", c: "Poland", z: "Europe/Warsaw", h: "华沙", a: ["Warszawa"] },
    { n: "Krakow", c: "Poland", z: "Europe/Warsaw", h: "克拉科夫", a: ["Kraków"] },
    { n: "Prague", c: "Czechia", z: "Europe/Prague", h: "布拉格", a: ["Praha"] },
    { n: "Budapest", c: "Hungary", z: "Europe/Budapest", h: "布达佩斯" },
    { n: "Bucharest", c: "Romania", z: "Europe/Bucharest", h: "布加勒斯特", a: ["București"] },
    { n: "Sofia", c: "Bulgaria", z: "Europe/Sofia", h: "索非亚" },
    { n: "Athens", c: "Greece", z: "Europe/Athens", h: "雅典" },
    { n: "Thessaloniki", c: "Greece", z: "Europe/Athens", h: "塞萨洛尼基" },
    { n: "Belgrade", c: "Serbia", z: "Europe/Belgrade", h: "贝尔格莱德", a: ["Beograd"] },
    { n: "Zagreb", c: "Croatia", z: "Europe/Zagreb", h: "萨格勒布" },
    { n: "Ljubljana", c: "Slovenia", z: "Europe/Ljubljana", h: "卢布尔雅那" },
    { n: "Bratislava", c: "Slovakia", z: "Europe/Bratislava", h: "布拉迪斯拉发" },
    { n: "Vilnius", c: "Lithuania", z: "Europe/Vilnius", h: "维尔纽斯" },
    { n: "Riga", c: "Latvia", z: "Europe/Riga", h: "里加" },
    { n: "Tallinn", c: "Estonia", z: "Europe/Tallinn", h: "塔林" },
    { n: "Kyiv", c: "Ukraine", z: "Europe/Kyiv", h: "基辅", a: ["Kiev"] },
    { n: "Lviv", c: "Ukraine", z: "Europe/Kyiv", h: "利沃夫" },
    { n: "Minsk", c: "Belarus", z: "Europe/Minsk", h: "明斯克" },
    { n: "Chisinau", c: "Moldova", z: "Europe/Chisinau", h: "基希讷乌", a: ["Chișinău"] },
    { n: "Valletta", c: "Malta", z: "Europe/Malta", h: "瓦莱塔", a: ["Malta", "马耳他"] },
    { n: "Monaco", c: "Monaco", z: "Europe/Monaco", h: "摩纳哥" },
    /* -------- Russia -------- */
    { n: "Moscow", c: "Russia", z: "Europe/Moscow", h: "莫斯科", a: ["Москва"] },
    { n: "Saint Petersburg", c: "Russia", z: "Europe/Moscow", h: "圣彼得堡", a: ["St Petersburg", "彼得堡"] },
    { n: "Kazan", c: "Russia", z: "Europe/Moscow", h: "喀山" },
    { n: "Yekaterinburg", c: "Russia", z: "Asia/Yekaterinburg", h: "叶卡捷琳堡" },
    { n: "Novosibirsk", c: "Russia", z: "Asia/Novosibirsk", h: "新西伯利亚" },
    { n: "Irkutsk", c: "Russia", z: "Asia/Irkutsk", h: "伊尔库茨克" },
    { n: "Vladivostok", c: "Russia", z: "Asia/Vladivostok", h: "符拉迪沃斯托克", a: ["海参崴"] },
    /* -------- Caucasus & Central Asia -------- */
    { n: "Baku", c: "Azerbaijan", z: "Asia/Baku", h: "巴库" },
    { n: "Tbilisi", c: "Georgia", z: "Asia/Tbilisi", h: "第比利斯" },
    { n: "Yerevan", c: "Armenia", z: "Asia/Yerevan", h: "埃里温" },
    { n: "Almaty", c: "Kazakhstan", z: "Asia/Almaty", h: "阿拉木图" },
    { n: "Astana", c: "Kazakhstan", z: "Asia/Almaty", h: "阿斯塔纳", a: ["Nur-Sultan", "努尔苏丹"] },
    { n: "Tashkent", c: "Uzbekistan", z: "Asia/Tashkent", h: "塔什干" },
    { n: "Bishkek", c: "Kyrgyzstan", z: "Asia/Bishkek", h: "比什凯克" },
    { n: "Dushanbe", c: "Tajikistan", z: "Asia/Dushanbe", h: "杜尚别" },
    { n: "Ashgabat", c: "Turkmenistan", z: "Asia/Ashgabat", h: "阿什哈巴德" },
    /* -------- Middle East -------- */
    { n: "Istanbul", c: "Turkey", z: "Europe/Istanbul", h: "伊斯坦布尔" },
    { n: "Ankara", c: "Turkey", z: "Europe/Istanbul", h: "安卡拉" },
    { n: "Dubai", c: "United Arab Emirates", z: "Asia/Dubai", h: "迪拜", a: ["杜拜"] },
    { n: "Abu Dhabi", c: "United Arab Emirates", z: "Asia/Dubai", h: "阿布扎比" },
    { n: "Doha", c: "Qatar", z: "Asia/Qatar", h: "多哈" },
    { n: "Riyadh", c: "Saudi Arabia", z: "Asia/Riyadh", h: "利雅得" },
    { n: "Jeddah", c: "Saudi Arabia", z: "Asia/Riyadh", h: "吉达" },
    { n: "Kuwait City", c: "Kuwait", z: "Asia/Kuwait", h: "科威特城" },
    { n: "Manama", c: "Bahrain", z: "Asia/Bahrain", h: "麦纳麦" },
    { n: "Muscat", c: "Oman", z: "Asia/Muscat", h: "马斯喀特" },
    { n: "Tel Aviv", c: "Israel", z: "Asia/Jerusalem", h: "特拉维夫" },
    { n: "Jerusalem", c: "Israel", z: "Asia/Jerusalem", h: "耶路撒冷" },
    { n: "Amman", c: "Jordan", z: "Asia/Amman", h: "安曼" },
    { n: "Beirut", c: "Lebanon", z: "Asia/Beirut", h: "贝鲁特" },
    { n: "Damascus", c: "Syria", z: "Asia/Damascus", h: "大马士革" },
    { n: "Baghdad", c: "Iraq", z: "Asia/Baghdad", h: "巴格达" },
    { n: "Tehran", c: "Iran", z: "Asia/Tehran", h: "德黑兰" },
    /* -------- Africa -------- */
    { n: "Cairo", c: "Egypt", z: "Africa/Cairo", h: "开罗" },
    { n: "Alexandria", c: "Egypt", z: "Africa/Cairo", h: "亚历山大" },
    { n: "Lagos", c: "Nigeria", z: "Africa/Lagos", h: "拉各斯" },
    { n: "Abuja", c: "Nigeria", z: "Africa/Lagos", h: "阿布贾" },
    { n: "Accra", c: "Ghana", z: "Africa/Accra", h: "阿克拉" },
    { n: "Abidjan", c: "Ivory Coast", z: "Africa/Abidjan", h: "阿比让" },
    { n: "Dakar", c: "Senegal", z: "Africa/Dakar", h: "达喀尔" },
    { n: "Casablanca", c: "Morocco", z: "Africa/Casablanca", h: "卡萨布兰卡" },
    { n: "Rabat", c: "Morocco", z: "Africa/Casablanca", h: "拉巴特" },
    { n: "Marrakesh", c: "Morocco", z: "Africa/Casablanca", h: "马拉喀什", a: ["Marrakech"] },
    { n: "Algiers", c: "Algeria", z: "Africa/Algiers", h: "阿尔及尔" },
    { n: "Tunis", c: "Tunisia", z: "Africa/Tunis", h: "突尼斯城" },
    { n: "Tripoli", c: "Libya", z: "Africa/Tripoli", h: "的黎波里" },
    { n: "Nairobi", c: "Kenya", z: "Africa/Nairobi", h: "内罗毕" },
    { n: "Addis Ababa", c: "Ethiopia", z: "Africa/Addis_Ababa", h: "亚的斯亚贝巴" },
    { n: "Dar es Salaam", c: "Tanzania", z: "Africa/Dar_es_Salaam", h: "达累斯萨拉姆" },
    { n: "Kampala", c: "Uganda", z: "Africa/Kampala", h: "坎帕拉" },
    { n: "Kigali", c: "Rwanda", z: "Africa/Kigali", h: "基加利" },
    { n: "Johannesburg", c: "South Africa", z: "Africa/Johannesburg", h: "约翰内斯堡", a: ["Joburg", "约堡"] },
    { n: "Cape Town", c: "South Africa", z: "Africa/Johannesburg", h: "开普敦" },
    { n: "Durban", c: "South Africa", z: "Africa/Johannesburg", h: "德班" },
    { n: "Pretoria", c: "South Africa", z: "Africa/Johannesburg", h: "比勒陀利亚" },
    { n: "Harare", c: "Zimbabwe", z: "Africa/Harare", h: "哈拉雷" },
    { n: "Lusaka", c: "Zambia", z: "Africa/Lusaka", h: "卢萨卡" },
    { n: "Gaborone", c: "Botswana", z: "Africa/Gaborone", h: "哈博罗内" },
    { n: "Windhoek", c: "Namibia", z: "Africa/Windhoek", h: "温得和克" },
    { n: "Maputo", c: "Mozambique", z: "Africa/Maputo", h: "马普托" },
    { n: "Luanda", c: "Angola", z: "Africa/Luanda", h: "罗安达" },
    { n: "Kinshasa", c: "DR Congo", z: "Africa/Kinshasa", h: "金沙萨" },
    { n: "Khartoum", c: "Sudan", z: "Africa/Khartoum", h: "喀土穆" },
    { n: "Port Louis", c: "Mauritius", z: "Indian/Mauritius", h: "路易港", a: ["Mauritius", "毛里求斯"] },
    { n: "Antananarivo", c: "Madagascar", z: "Indian/Antananarivo", h: "塔那那利佛" },
    /* -------- South Asia -------- */
    { n: "Mumbai", c: "India", z: "Asia/Kolkata", h: "孟买", a: ["Bombay"] },
    { n: "Delhi", c: "India", z: "Asia/Kolkata", h: "德里", a: ["New Delhi", "新德里"] },
    { n: "Bangalore", c: "India", z: "Asia/Kolkata", h: "班加罗尔", a: ["Bengaluru"] },
    { n: "Hyderabad", c: "India", z: "Asia/Kolkata", h: "海得拉巴" },
    { n: "Chennai", c: "India", z: "Asia/Kolkata", h: "金奈", a: ["Madras", "马德拉斯"] },
    { n: "Kolkata", c: "India", z: "Asia/Kolkata", h: "加尔各答", a: ["Calcutta"] },
    { n: "Pune", c: "India", z: "Asia/Kolkata", h: "浦那" },
    { n: "Ahmedabad", c: "India", z: "Asia/Kolkata", h: "艾哈迈达巴德" },
    { n: "Jaipur", c: "India", z: "Asia/Kolkata", h: "斋浦尔" },
    { n: "Karachi", c: "Pakistan", z: "Asia/Karachi", h: "卡拉奇" },
    { n: "Lahore", c: "Pakistan", z: "Asia/Karachi", h: "拉合尔" },
    { n: "Islamabad", c: "Pakistan", z: "Asia/Karachi", h: "伊斯兰堡" },
    { n: "Dhaka", c: "Bangladesh", z: "Asia/Dhaka", h: "达卡" },
    { n: "Chittagong", c: "Bangladesh", z: "Asia/Dhaka", h: "吉大港" },
    { n: "Colombo", c: "Sri Lanka", z: "Asia/Colombo", h: "科伦坡" },
    { n: "Kathmandu", c: "Nepal", z: "Asia/Kathmandu", h: "加德满都" },
    { n: "Thimphu", c: "Bhutan", z: "Asia/Thimphu", h: "廷布" },
    { n: "Male", c: "Maldives", z: "Indian/Maldives", h: "马累", a: ["Malé", "Maldives", "马尔代夫"] },
    /* -------- China (mainland → Asia/Shanghai, official national time) -------- */
    { n: "Beijing", c: "China", z: "Asia/Shanghai", h: "北京", a: ["Peking"] },
    { n: "Shanghai", c: "China", z: "Asia/Shanghai", h: "上海", a: ["沪"] },
    { n: "Guangzhou", c: "China", z: "Asia/Shanghai", h: "广州", a: ["Canton"] },
    { n: "Shenzhen", c: "China", z: "Asia/Shanghai", h: "深圳" },
    { n: "Chengdu", c: "China", z: "Asia/Shanghai", h: "成都" },
    { n: "Chongqing", c: "China", z: "Asia/Shanghai", h: "重庆", a: ["Chungking"] },
    { n: "Hangzhou", c: "China", z: "Asia/Shanghai", h: "杭州" },
    { n: "Wuhan", c: "China", z: "Asia/Shanghai", h: "武汉" },
    { n: "Xi'an", c: "China", z: "Asia/Shanghai", h: "西安", a: ["Xian"] },
    { n: "Nanjing", c: "China", z: "Asia/Shanghai", h: "南京", a: ["Nanking"] },
    { n: "Tianjin", c: "China", z: "Asia/Shanghai", h: "天津" },
    { n: "Suzhou", c: "China", z: "Asia/Shanghai", h: "苏州" },
    { n: "Qingdao", c: "China", z: "Asia/Shanghai", h: "青岛", a: ["Tsingtao"] },
    { n: "Dalian", c: "China", z: "Asia/Shanghai", h: "大连" },
    { n: "Xiamen", c: "China", z: "Asia/Shanghai", h: "厦门", a: ["Amoy"] },
    { n: "Changsha", c: "China", z: "Asia/Shanghai", h: "长沙" },
    { n: "Zhengzhou", c: "China", z: "Asia/Shanghai", h: "郑州" },
    { n: "Shenyang", c: "China", z: "Asia/Shanghai", h: "沈阳" },
    { n: "Harbin", c: "China", z: "Asia/Shanghai", h: "哈尔滨" },
    { n: "Kunming", c: "China", z: "Asia/Shanghai", h: "昆明" },
    { n: "Urumqi", c: "China", z: "Asia/Shanghai", h: "乌鲁木齐", a: ["Ürümqi"] },
    { n: "Lhasa", c: "China", z: "Asia/Shanghai", h: "拉萨" },
    /* -------- Hong Kong / Macau / Taiwan -------- */
    { n: "Hong Kong", c: "Hong Kong", z: "Asia/Hong_Kong", h: "香港", a: ["HK", "Hongkong"] },
    { n: "Macau", c: "Macau", z: "Asia/Macau", h: "澳门", a: ["Macao"] },
    { n: "Taipei", c: "Taiwan", z: "Asia/Taipei", h: "台北" },
    { n: "Kaohsiung", c: "Taiwan", z: "Asia/Taipei", h: "高雄" },
    { n: "Taichung", c: "Taiwan", z: "Asia/Taipei", h: "台中" },
    /* -------- Japan -------- */
    { n: "Tokyo", c: "Japan", z: "Asia/Tokyo", h: "东京", a: ["Tōkyō", "東京"] },
    { n: "Osaka", c: "Japan", z: "Asia/Tokyo", h: "大阪" },
    { n: "Kyoto", c: "Japan", z: "Asia/Tokyo", h: "京都" },
    { n: "Yokohama", c: "Japan", z: "Asia/Tokyo", h: "横滨", a: ["横浜"] },
    { n: "Nagoya", c: "Japan", z: "Asia/Tokyo", h: "名古屋" },
    { n: "Sapporo", c: "Japan", z: "Asia/Tokyo", h: "札幌" },
    { n: "Fukuoka", c: "Japan", z: "Asia/Tokyo", h: "福冈", a: ["福岡"] },
    { n: "Sendai", c: "Japan", z: "Asia/Tokyo", h: "仙台" },
    { n: "Hiroshima", c: "Japan", z: "Asia/Tokyo", h: "广岛", a: ["広島"] },
    { n: "Naha", c: "Japan", z: "Asia/Tokyo", h: "那霸", a: ["Okinawa", "冲绳"] },
    /* -------- Korea & Mongolia -------- */
    { n: "Seoul", c: "South Korea", z: "Asia/Seoul", h: "首尔", a: ["汉城", "서울"] },
    { n: "Busan", c: "South Korea", z: "Asia/Seoul", h: "釜山", a: ["Pusan"] },
    { n: "Incheon", c: "South Korea", z: "Asia/Seoul", h: "仁川" },
    { n: "Daegu", c: "South Korea", z: "Asia/Seoul", h: "大邱" },
    { n: "Pyongyang", c: "North Korea", z: "Asia/Pyongyang", h: "平壤" },
    { n: "Ulaanbaatar", c: "Mongolia", z: "Asia/Ulaanbaatar", h: "乌兰巴托", a: ["Ulan Bator"] },
    /* -------- Southeast Asia -------- */
    { n: "Singapore", c: "Singapore", z: "Asia/Singapore", h: "新加坡", a: ["SG", "狮城", "星洲"] },
    { n: "Kuala Lumpur", c: "Malaysia", z: "Asia/Kuala_Lumpur", h: "吉隆坡", a: ["KL"] },
    { n: "Penang", c: "Malaysia", z: "Asia/Kuala_Lumpur", h: "槟城", a: ["George Town", "槟榔屿"] },
    { n: "Bangkok", c: "Thailand", z: "Asia/Bangkok", h: "曼谷", a: ["Krung Thep"] },
    { n: "Chiang Mai", c: "Thailand", z: "Asia/Bangkok", h: "清迈" },
    { n: "Phuket", c: "Thailand", z: "Asia/Bangkok", h: "普吉", a: ["普吉岛"] },
    { n: "Jakarta", c: "Indonesia", z: "Asia/Jakarta", h: "雅加达" },
    { n: "Surabaya", c: "Indonesia", z: "Asia/Jakarta", h: "泗水" },
    { n: "Denpasar", c: "Indonesia", z: "Asia/Makassar", h: "登巴萨", a: ["Bali", "巴厘岛"] },
    { n: "Manila", c: "Philippines", z: "Asia/Manila", h: "马尼拉" },
    { n: "Cebu", c: "Philippines", z: "Asia/Manila", h: "宿务", a: ["宿雾"] },
    { n: "Hanoi", c: "Vietnam", z: "Asia/Ho_Chi_Minh", h: "河内", a: ["Hà Nội"] },
    { n: "Ho Chi Minh City", c: "Vietnam", z: "Asia/Ho_Chi_Minh", h: "胡志明市", a: ["Saigon", "HCMC", "西贡"] },
    { n: "Da Nang", c: "Vietnam", z: "Asia/Ho_Chi_Minh", h: "岘港", a: ["Đà Nẵng"] },
    { n: "Phnom Penh", c: "Cambodia", z: "Asia/Phnom_Penh", h: "金边" },
    { n: "Vientiane", c: "Laos", z: "Asia/Vientiane", h: "万象" },
    { n: "Yangon", c: "Myanmar", z: "Asia/Yangon", h: "仰光", a: ["Rangoon"] },
    { n: "Bandar Seri Begawan", c: "Brunei", z: "Asia/Brunei", h: "斯里巴加湾市", a: ["Brunei", "文莱"] },
    /* -------- Oceania & Pacific -------- */
    { n: "Sydney", c: "Australia", z: "Australia/Sydney", h: "悉尼", a: ["雪梨"] },
    { n: "Melbourne", c: "Australia", z: "Australia/Melbourne", h: "墨尔本" },
    { n: "Brisbane", c: "Australia", z: "Australia/Brisbane", h: "布里斯班" },
    { n: "Perth", c: "Australia", z: "Australia/Perth", h: "珀斯" },
    { n: "Adelaide", c: "Australia", z: "Australia/Adelaide", h: "阿德莱德" },
    { n: "Canberra", c: "Australia", z: "Australia/Sydney", h: "堪培拉" },
    { n: "Gold Coast", c: "Australia", z: "Australia/Brisbane", h: "黄金海岸" },
    { n: "Hobart", c: "Australia", z: "Australia/Hobart", h: "霍巴特" },
    { n: "Darwin", c: "Australia", z: "Australia/Darwin", h: "达尔文" },
    { n: "Auckland", c: "New Zealand", z: "Pacific/Auckland", h: "奥克兰" },
    { n: "Wellington", c: "New Zealand", z: "Pacific/Auckland", h: "惠灵顿" },
    { n: "Christchurch", c: "New Zealand", z: "Pacific/Auckland", h: "基督城" },
    { n: "Queenstown", c: "New Zealand", z: "Pacific/Auckland", h: "皇后镇" },
    { n: "Suva", c: "Fiji", z: "Pacific/Fiji", h: "苏瓦", a: ["Fiji", "斐济"] },
    { n: "Port Moresby", c: "Papua New Guinea", z: "Pacific/Port_Moresby", h: "莫尔兹比港" },
    { n: "Noumea", c: "New Caledonia", z: "Pacific/Noumea", h: "努美阿", a: ["Nouméa"] },
    { n: "Papeete", c: "French Polynesia", z: "Pacific/Tahiti", h: "帕皮提", a: ["Tahiti", "大溪地"] },
    { n: "Guam", c: "United States", z: "Pacific/Guam", h: "关岛", a: ["Hagåtña"] }
  ];

  function slug(s) {
    return s
      .normalize("NFD")
      .replace(/[\u0300-\u036f]/g, "")
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-+|-+$/g, "");
  }
  var seen = Object.create(null);
  for (var i = 0; i < C.length; i++) {
    var id = slug(C[i].n);
    if (seen[id]) id = id + "-" + slug(C[i].c);
    seen[id] = true;
    C[i].id = id;
    if (!C[i].a) C[i].a = [];
  }
  globalThis.CITIES = C;
})();
