/* Word Age — build-time-only marginalia (fun facts). Merged into the static
 * word pages by build.js; deliberately NOT shipped to the browser bundle to
 * keep the homepage under the 150KB page-weight budget. Same accuracy rules
 * as data.js. */
"use strict";
module.exports = {
"deer": "German kept the old meaning: Tier still means “animal.”",
"starve": "German sterben still means “to die.”",
"knight": "German Knecht still means “servant, farmhand.”",
"hound": "German Hund still means simply “dog.”",
"thing": "Iceland’s parliament is still the Alþingi — the “all-thing.”",
"apple": "Genesis never names the forbidden fruit; “apple” filled the blank because apple once meant fruit.",
"craft": "German Kraft still means “power” — as in Kraftwerk, “power station.”",
"gift": "In modern German, Gift means “poison” — a gift gone very wrong.",
"harvest": "German Herbst still means “autumn.”",
"tide": "“Time and tide wait for no man” originally said the same thing twice.",
"lust": "German kept the innocence: Lust still means “joy, desire” — Wanderlust is just “joy of hiking.”",
"friend": "“Unfriend” is not a Facebook invention — as a noun meaning “enemy,” it appears in Middle English centuries earlier.",
"fee": "Latin did the same: pecunia “money” comes from pecu “cattle.”",
"smirk": "For centuries English could smirk but not smile — the older word is the sneaky one.",
"sibling": "Modern “sibling” is a 20th-century scientific resurrection of a dead Old English word.",
"island": "The s in island has never been pronounced. It was pasted in by error around the 16th century.",
"noon": "Noon used to be mid-afternoon. The meal moved, and the word moved with it.",
"nice": "For its first three centuries, calling someone nice meant calling them a fool.",
"girl": "A medieval “girl” could be a boy. “Boy” meanwhile meant a servant.",
"awful": "“Awful” and “awesome” were once near-synonyms. They split custody of awe.",
"ace": "Ace flipped from “worthless” to “excellent” because card players decided one beats everything.",
"influence": "Every influencer is, etymologically, a minor celestial body.",
"happy": "“Happy” and “happen” are siblings: both children of hap, “luck.”",
"nightmare": "The mare in nightmare is a demon, not a horse.",
"travel": "Travel and travail are one word. Airlines have changed nothing.",
"news": "The NEWS-as-compass-points etymology is false. It’s just “new,” pluralized.",
"mortgage": "Every mortgage contains the French word for death.",
"dinner": "Dinner literally means breakfast. The meal just kept getting later.",
"orange": "The fruit named the color, not the other way around.",
"car": "“Car” predates the automobile by roughly 600 years.",
"smile": "English could smirk for centuries before it learned to smile.",
"skirt": "Shirt and skirt are one word that immigrated twice.",
"troll": "The internet troll is fishing vocabulary, not the bridge monster — though the monster helped it stick.",
"clue": "Every detective’s clue is Ariadne’s ball of string.",
"bully": "“Bully for you!” preserves the old good bully — as does Roosevelt’s “bully pulpit.”",
"utopia": "Utopia literally means “nowhere.” The joke was built in from day one.",
"shark": "Nobody knows where “shark” comes from. The card shark may be from a different word entirely (German Schurke, “scoundrel”).",
"turkey": "In Turkey the bird is “hindi” — India. Nearly every language blames somewhere else.",
"potato": "The original potato was the sweet potato. The ordinary spud is the impostor.",
"alcohol": "Alcohol originally meant eye makeup.",
"sincere": "The “without wax” story is a myth. Latin sincerus just meant pure.",
"dunce": "The dunce cap is named after a genius.",
"explode": "The first things ever exploded were actors.",
"computer": "“Computer” was a profession for 300 years before it was a device.",
"pandemic": "“Pandemic” is older than the United States by over a century.",
"fun": "Shakespeare never had fun. The word arrived seven decades after his death — and meant fraud.",
"punk": "Punk is in Measure for Measure. Shakespeare got there nearly four centuries before the Sex Pistols.",
"tea": "Whether a country says “tea” or “chai” tells you if the leaves arrived by sea or by land.",
"recipe": "The pharmacy symbol ℞ and your cookie recipe are the same word.",
"weekend": "“Weekend” existed 250 years before anyone got Saturdays off.",
"manufacture": "“Manufactured” literally means handmade.",
"ketchup": "The original ketchup contained fish, and no tomatoes whatsoever.",
"literally": "People have used “literally” figuratively since the 1700s. The outrage is younger than the crime.",
"tank": "The war machine is named after a water tank — a WWI secrecy codename that stuck.",
"bug": "Grace Hopper’s 1947 moth taped in a logbook popularized, but did not coin, the computer bug — engineers had bugs 70 years earlier.",
"boredom": "“Boredom” is younger than the steam locomotive — Jane Austen lived her whole life without the word.",
"scientist": "Darwin sailed on the Beagle before the word “scientist” existed.",
"hello": "Bell wanted us to answer the phone with “Ahoy.” Hello won.",
"ok": "OK started as a deliberate misspelling joke — “all correct” → “oll korrect.”",
"teenager": "Teenagers are younger than sliced bread (1928) — the word, anyway.",
"snob": "A snob was originally at the bottom of the ladder, not sneering from the top.",
"serendipity": "One man invented “serendipity” in a private letter. It stayed rare until the 20th century.",
"vaccine": "Vaccine literally means “from a cow” — in honor of the original cowpox inoculation.",
"boycott": "Captain Boycott was boycotted so effectively his name became the word — in under a year.",
"shampoo": "The first shampoos washed nothing — they were massages.",
"jungle": "Jungle originally meant something closer to desert.",
"avatar": "Your forum avatar is, etymologically, a god taking mortal form.",
"vampire": "“Vampire” entered English via 1730s tabloid coverage of actual exhumations.",
"glamour": "Glamour and grammar are the same word. Learning looked like sorcery.",
"robot": "“Robot” comes from a 1920 play — and the robots revolt in it.",
"astronaut": "“Astronaut” predates spaceflight by 30 years.",
"camera": "A camera is, literally, a room. Early photographers stood inside theirs.",
"podcast": "Podcasts are named after a discontinued MP3 player.",
"spam": "Junk email is named after a Monty Python sketch about canned meat.",
"bus": "“Bus” is a Latin suffix driving around without its word.",
"airplane": "“Aeroplane” (1866) is older than powered flight by 37 years — coined for designs that couldn’t yet fly.",
"helicopter": "The word helicopter is 60 years older than the working helicopter.",
"soccer": "“Soccer” is British slang. Blaming Americans for it is historically unfair.",
"baseball": "Baseball is first recorded in England, decades before the USA existed.",
"hamburger": "There is no ham in a hamburger. There is a German city.",
"restaurant": "Restaurants are named after soup that claimed to restore your health.",
"cocktail": "The first printed definition of “cocktail” (1806) called it an “electioneering potion.”",
"nerd": "“Nerd” was coined by Dr. Seuss. Probably.",
"geek": "The original geeks worked the freak show, biting heads off live chickens.",
"dude": "The first dudes were Victorian fashion victims.",
"jazz": "“Jazz” first appears in print describing a baseball pitch, not music.",
"factoid": "“Factoid” originally meant a fact that ISN’T true.",
"deadline": "The first deadlines were enforced with rifles.",
"freelance": "“Freelancer” was invented in a novel, describing mercenaries.",
"oxygen": "Oxygen is named for a chemistry mistake.",
"helium": "Helium was discovered on the sun first. Earth caught up in 1895.",
"taser": "The Taser is named after a boys’ adventure novel from 1911.",
"pants": "Pants descend from the name of an Italian comedy character.",
"pink": "English had no word for pink until the 18th century.",
"kangaroo": "“Kangaroo” does not mean “I don’t know.” That legend is false; it names a large black kangaroo.",
"octopus": "“Octopi” is etymologically wrong — the word is Greek, not Latin.",
"karaoke": "Karaoke means “empty orchestra” — the same “empty” as in karate.",
"tycoon": "Abraham Lincoln’s staff called him “the Tycoon” before businessmen claimed the word.",
"piano": "Piano is short for “soft-loud.” The instrument is named after its volume knob.",
"cool": "“Cool” as praise is from Black American jazz slang of the 1930s–40s; the word itself is over a thousand years old.",
"dord": "Dord never existed. It’s the most famous accidental word in lexicography — printed in Webster’s from 1934 to 1939.",
"jumbo": "Jumbo jets are named after one specific Victorian elephant."
};
