// At Your Age — milestone dataset.
// Curation rules (see PLAYBOOK.md):
//   * only widely reported, publicly verifiable facts; age computed from public
//     birth date and event date (year precision unless ageDays is given);
//   * mode "roast" = early achiever (stings), mode "heal" = late bloomer (soothes);
//   * event is a simple-past verb phrase without subject, no trailing period;
//   * `p` is the pronoun ("he"/"she"), `short` the everyday name;
//   * optional `ageDays` = exact age in days at the event (leap-year aware);
//   * optional `death: true` routes the entry through the dynamic death templates;
//   * optional `future` = bare verb phrase for the HEAL template
//     "At your age, X wouldn't {future} for another N years."
// If a fact could not be pinned to a defensible age, it was not included.

const AYA_MILESTONES = [
  // ---------------------------------------------------------------- ROAST ---
  { id: "mozart-minuets", person: "Wolfgang Amadeus Mozart", short: "Mozart", p: "he", age: 5, event: "composed his first minuets", year: 1761, mode: "roast", category: "music" },
  { id: "mozart-symphony", person: "Wolfgang Amadeus Mozart", short: "Mozart", p: "he", age: 8, event: "wrote his first symphony", year: 1764, mode: "roast", category: "music" },
  { id: "mozart-dead", person: "Wolfgang Amadeus Mozart", short: "Mozart", p: "he", age: 35, ageDays: 13096, event: "died, with more than 600 finished works to his name", year: 1791, mode: "roast", category: "music", death: true },
  { id: "alexander-king", person: "Alexander the Great", short: "Alexander the Great", p: "he", age: 20, event: "became king of Macedon", year: "336 BC", mode: "roast", category: "politics" },
  { id: "alexander-empire", person: "Alexander the Great", short: "Alexander", p: "he", age: 25, event: "had conquered the Persian Empire", year: "331 BC", mode: "roast", category: "politics" },
  { id: "alexander-dead", person: "Alexander the Great", short: "Alexander the Great", p: "he", age: 32, event: "died undefeated in battle", year: "323 BC", mode: "roast", category: "politics", death: true },
  { id: "tutankhamun-pharaoh", person: "Tutankhamun", short: "Tutankhamun", p: "he", age: 9, event: "became pharaoh of Egypt", year: "c. 1332 BC", mode: "roast", category: "politics" },
  { id: "cleopatra-queen", person: "Cleopatra", short: "Cleopatra", p: "she", age: 18, event: "became queen of Egypt", year: "51 BC", mode: "roast", category: "politics" },
  { id: "joan-orleans", person: "Joan of Arc", short: "Joan of Arc", p: "she", age: 17, event: "led the army that broke the siege of Orléans", year: 1429, mode: "roast", category: "politics" },
  { id: "victoria-queen", person: "Queen Victoria", short: "Victoria", p: "she", age: 18, event: "became Queen of the United Kingdom", year: 1837, mode: "roast", category: "politics" },
  { id: "pitt-pm", person: "William Pitt the Younger", short: "Pitt the Younger", p: "he", age: 24, event: "became British prime minister", year: 1783, mode: "roast", category: "politics" },
  { id: "napoleon-general", person: "Napoleon Bonaparte", short: "Napoleon", p: "he", age: 24, event: "was a general in the French army", year: 1793, mode: "roast", category: "politics" },
  { id: "napoleon-emperor", person: "Napoleon Bonaparte", short: "Napoleon", p: "he", age: 35, event: "crowned himself Emperor of the French", year: 1804, mode: "roast", category: "politics" },
  { id: "troosevelt-president", person: "Theodore Roosevelt", short: "Theodore Roosevelt", p: "he", age: 42, event: "was sworn in as the youngest US president in history", year: 1901, mode: "roast", category: "politics" },
  { id: "jfk-president", person: "John F. Kennedy", short: "JFK", p: "he", age: 43, event: "was elected president of the United States", year: 1960, mode: "roast", category: "politics" },
  { id: "mlk-boycott", person: "Martin Luther King Jr.", short: "Dr. King", p: "he", age: 26, event: "was leading the Montgomery bus boycott", year: 1955, mode: "roast", category: "politics" },
  { id: "mlk-dream", person: "Martin Luther King Jr.", short: "Dr. King", p: "he", age: 34, event: "delivered “I Have a Dream” to a quarter of a million people", year: 1963, mode: "roast", category: "politics" },
  { id: "mlk-nobel", person: "Martin Luther King Jr.", short: "Dr. King", p: "he", age: 35, event: "won the Nobel Peace Prize", year: 1964, mode: "roast", category: "politics" },
  { id: "malala-nobel", person: "Malala Yousafzai", short: "Malala", p: "she", age: 17, event: "won the Nobel Peace Prize", year: 2014, mode: "roast", category: "politics" },
  { id: "zuckerberg-facebook", person: "Mark Zuckerberg", short: "Zuckerberg", p: "he", age: 19, event: "launched Facebook from a dorm room", year: 2004, mode: "roast", category: "tech" },
  { id: "gates-microsoft", person: "Bill Gates", short: "Bill Gates", p: "he", age: 19, event: "co-founded Microsoft", year: 1975, mode: "roast", category: "tech" },
  { id: "jobs-apple", person: "Steve Jobs", short: "Steve Jobs", p: "he", age: 21, event: "co-founded Apple", year: 1976, mode: "roast", category: "tech" },
  { id: "jobs-macintosh", person: "Steve Jobs", short: "Steve Jobs", p: "he", age: 28, event: "unveiled the Macintosh", year: 1984, mode: "roast", category: "tech" },
  { id: "wozniak-apple1", person: "Steve Wozniak", short: "Wozniak", p: "he", age: 25, event: "designed the Apple I single-handedly", year: 1976, mode: "roast", category: "tech" },
  { id: "page-google", person: "Larry Page", short: "Larry Page", p: "he", age: 25, event: "co-founded Google", year: 1998, mode: "roast", category: "tech" },
  { id: "spiegel-billionaire", person: "Evan Spiegel", short: "Evan Spiegel", p: "he", age: 24, event: "was the world's youngest billionaire", year: 2015, mode: "roast", category: "business" },
  { id: "kamprad-ikea", person: "Ingvar Kamprad", short: "Ingvar Kamprad", p: "he", age: 17, event: "founded IKEA", year: 1943, mode: "roast", category: "business" },
  { id: "branson-virgin", person: "Richard Branson", short: "Branson", p: "he", age: 22, event: "founded Virgin Records", year: 1972, mode: "roast", category: "business" },
  { id: "buffett-firststock", person: "Warren Buffett", short: "Warren Buffett", p: "he", age: 11, event: "bought his first stock", year: 1942, mode: "roast", category: "business" },
  { id: "chanel-shop", person: "Coco Chanel", short: "Coco Chanel", p: "she", age: 26, event: "opened her first shop in Paris", year: 1910, mode: "roast", category: "fashion" },
  { id: "ysl-dior", person: "Yves Saint Laurent", short: "Saint Laurent", p: "he", age: 21, event: "was head designer of the house of Dior", year: 1957, mode: "roast", category: "fashion" },
  { id: "disney-mickey", person: "Walt Disney", short: "Walt Disney", p: "he", age: 26, event: "created Mickey Mouse", year: 1928, mode: "roast", category: "film" },
  { id: "chaplin-ua", person: "Charlie Chaplin", short: "Chaplin", p: "he", age: 29, event: "co-founded United Artists", year: 1919, mode: "roast", category: "film" },
  { id: "welles-kane", person: "Orson Welles", short: "Orson Welles", p: "he", age: 25, event: "co-wrote, directed and starred in Citizen Kane", year: 1941, mode: "roast", category: "film" },
  { id: "spielberg-jaws", person: "Steven Spielberg", short: "Spielberg", p: "he", age: 28, event: "directed Jaws", year: 1975, mode: "roast", category: "film" },
  { id: "lucas-starwars", person: "George Lucas", short: "George Lucas", p: "he", age: 33, event: "wrote and directed Star Wars", year: 1977, mode: "roast", category: "film" },
  { id: "temple-oscar", person: "Shirley Temple", short: "Shirley Temple", p: "she", age: 6, event: "received an honorary Academy Award", year: 1935, mode: "roast", category: "film" },
  { id: "einstein-relativity", person: "Albert Einstein", short: "Einstein", p: "he", age: 26, event: "published the special theory of relativity", year: 1905, mode: "roast", category: "science" },
  { id: "newton-calculus", person: "Isaac Newton", short: "Newton", p: "he", age: 23, event: "worked out the foundations of calculus during a plague quarantine", year: 1666, mode: "roast", category: "science" },
  { id: "curie-nobel1", person: "Marie Curie", short: "Marie Curie", p: "she", age: 36, event: "won her first Nobel Prize", year: 1903, mode: "roast", category: "science" },
  { id: "curie-nobel2", person: "Marie Curie", short: "Marie Curie", p: "she", age: 44, event: "won her second Nobel Prize, in a second science", year: 1911, mode: "roast", category: "science" },
  { id: "bragg-nobel", person: "Lawrence Bragg", short: "Lawrence Bragg", p: "he", age: 25, event: "won the Nobel Prize in Physics, still the youngest science laureate ever", year: 1915, mode: "roast", category: "science" },
  { id: "dirac-nobel", person: "Paul Dirac", short: "Dirac", p: "he", age: 31, event: "won the Nobel Prize in Physics", year: 1933, mode: "roast", category: "science" },
  { id: "heisenberg-matrix", person: "Werner Heisenberg", short: "Heisenberg", p: "he", age: 23, event: "invented matrix quantum mechanics", year: 1925, mode: "roast", category: "science" },
  { id: "ramanujan-letter", person: "Srinivasa Ramanujan", short: "Ramanujan", p: "he", age: 25, event: "mailed the theorems that stunned Cambridge", year: 1913, mode: "roast", category: "science" },
  { id: "galois-groups", person: "Évariste Galois", short: "Galois", p: "he", age: 20, event: "had laid the foundations of group theory", year: 1832, mode: "roast", category: "science" },
  { id: "pascal-calculator", person: "Blaise Pascal", short: "Pascal", p: "he", age: 19, event: "invented a working mechanical calculator", year: 1642, mode: "roast", category: "science" },
  { id: "lovelace-algorithm", person: "Ada Lovelace", short: "Ada Lovelace", p: "she", age: 27, event: "published the first computer algorithm", year: 1843, mode: "roast", category: "tech" },
  { id: "braille-code", person: "Louis Braille", short: "Louis Braille", p: "he", age: 15, event: "invented the braille reading system", year: 1824, mode: "roast", category: "science" },
  { id: "bell-telephone", person: "Alexander Graham Bell", short: "Bell", p: "he", age: 29, event: "patented the telephone", year: 1876, mode: "roast", category: "tech" },
  { id: "edison-phonograph", person: "Thomas Edison", short: "Edison", p: "he", age: 30, event: "invented the phonograph", year: 1877, mode: "roast", category: "tech" },
  { id: "farnsworth-tv", person: "Philo Farnsworth", short: "Philo Farnsworth", p: "he", age: 21, event: "demonstrated the first electronic television", year: 1927, mode: "roast", category: "tech" },
  { id: "wright-flight", person: "Orville Wright", short: "Orville Wright", p: "he", age: 32, event: "flew the first powered airplane", year: 1903, mode: "roast", category: "exploration" },
  { id: "gagarin-space", person: "Yuri Gagarin", short: "Gagarin", p: "he", age: 27, event: "became the first human in space", year: 1961, mode: "roast", category: "exploration" },
  { id: "ride-space", person: "Sally Ride", short: "Sally Ride", p: "she", age: 32, event: "became the youngest American in space", year: 1983, mode: "roast", category: "exploration" },
  { id: "armstrong-moon", person: "Neil Armstrong", short: "Neil Armstrong", p: "he", age: 38, event: "walked on the Moon", year: 1969, mode: "roast", category: "exploration" },
  { id: "glenn-orbit", person: "John Glenn", short: "John Glenn", p: "he", age: 40, event: "became the first American to orbit the Earth", year: 1962, mode: "roast", category: "exploration" },
  { id: "hillary-everest", person: "Edmund Hillary", short: "Edmund Hillary", p: "he", age: 33, event: "stood on the summit of Everest", year: 1953, mode: "roast", category: "exploration" },
  { id: "darwin-beagle", person: "Charles Darwin", short: "Darwin", p: "he", age: 22, event: "set sail on the Beagle", year: 1831, mode: "roast", category: "exploration" },
  { id: "goodall-gombe", person: "Jane Goodall", short: "Jane Goodall", p: "she", age: 26, event: "began the chimpanzee study that rewrote biology", year: 1960, mode: "roast", category: "science" },
  { id: "tao-imo", person: "Terence Tao", short: "Terence Tao", p: "he", age: 13, event: "won an International Mathematical Olympiad gold medal", year: 1988, mode: "roast", category: "science" },
  { id: "mshelley-frankenstein", person: "Mary Shelley", short: "Mary Shelley", p: "she", age: 18, event: "began writing Frankenstein", year: 1816, mode: "roast", category: "literature" },
  { id: "keats-odes", person: "John Keats", short: "Keats", p: "he", age: 23, event: "had written all six of his great odes", year: 1819, mode: "roast", category: "literature" },
  { id: "rimbaud-quit", person: "Arthur Rimbaud", short: "Rimbaud", p: "he", age: 20, event: "had written his entire poetic legacy — and quit", year: 1875, mode: "roast", category: "literature" },
  { id: "hinton-outsiders", person: "S. E. Hinton", short: "S. E. Hinton", p: "she", age: 16, event: "wrote The Outsiders", year: 1965, mode: "roast", category: "literature" },
  { id: "fitzgerald-paradise", person: "F. Scott Fitzgerald", short: "Fitzgerald", p: "he", age: 23, event: "published This Side of Paradise", year: 1920, mode: "roast", category: "literature" },
  { id: "fitzgerald-gatsby", person: "F. Scott Fitzgerald", short: "Fitzgerald", p: "he", age: 28, event: "published The Great Gatsby", year: 1925, mode: "roast", category: "literature" },
  { id: "austen-draft", person: "Jane Austen", short: "Jane Austen", p: "she", age: 21, event: "drafted Pride and Prejudice", year: 1797, mode: "roast", category: "literature" },
  { id: "paolini-eragon", person: "Christopher Paolini", short: "Paolini", p: "he", age: 15, event: "began writing Eragon", year: 1999, mode: "roast", category: "literature" },
  { id: "picasso-demoiselles", person: "Pablo Picasso", short: "Picasso", p: "he", age: 25, event: "painted Les Demoiselles d'Avignon", year: 1907, mode: "roast", category: "art" },
  { id: "michelangelo-pieta", person: "Michelangelo", short: "Michelangelo", p: "he", age: 24, event: "carved the Pietà", year: 1499, mode: "roast", category: "art" },
  { id: "mendelssohn-octet", person: "Felix Mendelssohn", short: "Mendelssohn", p: "he", age: 16, event: "composed his Octet", year: 1825, mode: "roast", category: "music" },
  { id: "chopin-polonaise", person: "Frédéric Chopin", short: "Chopin", p: "he", age: 7, event: "composed his first polonaise", year: 1817, mode: "roast", category: "music" },
  { id: "clara-debut", person: "Clara Schumann", short: "Clara Schumann", p: "she", age: 9, event: "gave her first public concert", year: 1828, mode: "roast", category: "music" },
  { id: "yoyoma-kennedy", person: "Yo-Yo Ma", short: "Yo-Yo Ma", p: "he", age: 7, event: "performed for President Kennedy", year: 1962, mode: "roast", category: "music" },
  { id: "schubert-erlkonig", person: "Franz Schubert", short: "Schubert", p: "he", age: 18, event: "composed “Erlkönig”", year: 1815, mode: "roast", category: "music" },
  { id: "mjackson-number1", person: "Michael Jackson", short: "Michael Jackson", p: "he", age: 11, event: "hit No. 1 with the Jackson 5", year: 1970, mode: "roast", category: "music" },
  { id: "mjackson-thriller", person: "Michael Jackson", short: "Michael Jackson", p: "he", age: 24, event: "released Thriller", year: 1982, mode: "roast", category: "music" },
  { id: "stevie-fingertips", person: "Stevie Wonder", short: "Stevie Wonder", p: "he", age: 13, event: "topped the charts with “Fingertips”", year: 1963, mode: "roast", category: "music" },
  { id: "aretha-album", person: "Aretha Franklin", short: "Aretha Franklin", p: "she", age: 14, event: "recorded her first album", year: 1956, mode: "roast", category: "music" },
  { id: "swift-debut", person: "Taylor Swift", short: "Taylor Swift", p: "she", age: 16, event: "released her debut album", year: 2006, mode: "roast", category: "music" },
  { id: "lorde-royals", person: "Lorde", short: "Lorde", p: "she", age: 16, event: "topped the US charts with “Royals”", year: 2013, mode: "roast", category: "music" },
  { id: "eilish-grammys", person: "Billie Eilish", short: "Billie Eilish", p: "she", age: 18, event: "swept all four major Grammy categories", year: 2020, mode: "roast", category: "music" },
  { id: "adele-21", person: "Adele", short: "Adele", p: "she", age: 22, event: "released 21", year: 2011, mode: "roast", category: "music" },
  { id: "beyonce-grammys", person: "Beyoncé", short: "Beyoncé", p: "she", age: 19, event: "won her first two Grammys", year: 2001, mode: "roast", category: "music" },
  { id: "whitney-number1", person: "Whitney Houston", short: "Whitney Houston", p: "she", age: 22, event: "had her first No. 1 single", year: 1985, mode: "roast", category: "music" },
  { id: "mccartney-yesterday", person: "Paul McCartney", short: "McCartney", p: "he", age: 22, event: "recorded “Yesterday”", year: 1965, mode: "roast", category: "music" },
  { id: "dylan-freewheelin", person: "Bob Dylan", short: "Bob Dylan", p: "he", age: 22, event: "released The Freewheelin' Bob Dylan", year: 1963, mode: "roast", category: "music" },
  { id: "pele-worldcup", person: "Pelé", short: "Pelé", p: "he", age: 17, event: "won the World Cup", year: 1958, mode: "roast", category: "sports" },
  { id: "mbappe-worldcup", person: "Kylian Mbappé", short: "Mbappé", p: "he", age: 19, event: "won the World Cup", year: 2018, mode: "roast", category: "sports" },
  { id: "messi-debut", person: "Lionel Messi", short: "Messi", p: "he", age: 17, event: "made his debut for FC Barcelona", year: 2004, mode: "roast", category: "sports" },
  { id: "bolt-record", person: "Usain Bolt", short: "Usain Bolt", p: "he", age: 21, event: "set the 100 m world record", year: 2008, mode: "roast", category: "sports" },
  { id: "comaneci-ten", person: "Nadia Comăneci", short: "Nadia Comăneci", p: "she", age: 14, event: "scored the first perfect 10 in Olympic history", year: 1976, mode: "roast", category: "sports" },
  { id: "biles-worlds", person: "Simone Biles", short: "Simone Biles", p: "she", age: 16, event: "was world all-around champion", year: 2013, mode: "roast", category: "sports" },
  { id: "ledecky-gold", person: "Katie Ledecky", short: "Katie Ledecky", p: "she", age: 15, event: "won Olympic gold", year: 2012, mode: "roast", category: "sports" },
  { id: "phelps-eight", person: "Michael Phelps", short: "Michael Phelps", p: "he", age: 23, event: "won eight golds at a single Olympics", year: 2008, mode: "roast", category: "sports" },
  { id: "serena-slam", person: "Serena Williams", short: "Serena Williams", p: "she", age: 17, event: "won her first Grand Slam title", year: 1999, mode: "roast", category: "sports" },
  { id: "woods-masters", person: "Tiger Woods", short: "Tiger Woods", p: "he", age: 21, event: "won the Masters", year: 1997, mode: "roast", category: "sports" },
  { id: "becker-wimbledon", person: "Boris Becker", short: "Boris Becker", p: "he", age: 17, event: "won Wimbledon", year: 1985, mode: "roast", category: "sports" },
  { id: "nadal-french", person: "Rafael Nadal", short: "Rafael Nadal", p: "he", age: 19, event: "won the French Open", year: 2005, mode: "roast", category: "sports" },
  { id: "ali-champion", person: "Muhammad Ali", short: "Muhammad Ali", p: "he", age: 22, event: "was heavyweight champion of the world", year: 1964, mode: "roast", category: "sports" },
  { id: "tyson-champion", person: "Mike Tyson", short: "Mike Tyson", p: "he", age: 20, event: "became the youngest heavyweight champion ever", year: 1986, mode: "roast", category: "sports" },
  { id: "gretzky-92", person: "Wayne Gretzky", short: "Gretzky", p: "he", age: 21, event: "scored 92 goals in one NHL season", year: 1982, mode: "roast", category: "sports" },
  { id: "lebron-debut", person: "LeBron James", short: "LeBron", p: "he", age: 18, event: "made his NBA debut", year: 2003, mode: "roast", category: "sports" },
  { id: "owens-berlin", person: "Jesse Owens", short: "Jesse Owens", p: "he", age: 22, event: "won four Olympic golds in Berlin", year: 1936, mode: "roast", category: "sports" },
  { id: "kim-gold", person: "Chloe Kim", short: "Chloe Kim", p: "she", age: 17, event: "won Olympic halfpipe gold", year: 2018, mode: "roast", category: "sports" },
  { id: "carlsen-gm", person: "Magnus Carlsen", short: "Magnus Carlsen", p: "he", age: 13, event: "became a chess grandmaster", year: 2004, mode: "roast", category: "sports" },
  { id: "kasparov-champion", person: "Garry Kasparov", short: "Kasparov", p: "he", age: 22, event: "became world chess champion", year: 1985, mode: "roast", category: "sports" },
  { id: "polgar-gm", person: "Judit Polgár", short: "Judit Polgár", p: "she", age: 15, event: "became a grandmaster, breaking Bobby Fischer's record", year: 1991, mode: "roast", category: "sports" },
  { id: "fischer-gm", person: "Bobby Fischer", short: "Bobby Fischer", p: "he", age: 15, event: "became a chess grandmaster", year: 1958, mode: "roast", category: "sports" },

  // ----------------------------------------------------------------- HEAL ---
  { id: "moses-painting", person: "Grandma Moses", short: "Grandma Moses", p: "she", age: 76, event: "began painting in earnest", year: 1936, mode: "heal", category: "art", future: "pick up a brush in earnest" },
  { id: "moses-show", person: "Grandma Moses", short: "Grandma Moses", p: "she", age: 80, event: "had her first solo show in New York", year: 1940, mode: "heal", category: "art", future: "get her first solo show" },
  { id: "sanders-franchise", person: "Colonel Harland Sanders", short: "Colonel Sanders", p: "he", age: 62, event: "started franchising his fried-chicken recipe", year: 1952, mode: "heal", category: "food", future: "start franchising his chicken" },
  { id: "sanders-sale", person: "Colonel Harland Sanders", short: "Colonel Sanders", p: "he", age: 73, event: "sold KFC for two million dollars", year: 1964, mode: "heal", category: "food" },
  { id: "wang-dress", person: "Vera Wang", short: "Vera Wang", p: "she", age: 40, event: "designed her first dress", year: 1990, mode: "heal", category: "fashion", future: "design her first dress" },
  { id: "child-book", person: "Julia Child", short: "Julia Child", p: "she", age: 49, event: "published her first cookbook", year: 1961, mode: "heal", category: "food", future: "publish her first cookbook" },
  { id: "child-tv", person: "Julia Child", short: "Julia Child", p: "she", age: 50, event: "made her television debut", year: 1963, mode: "heal", category: "food" },
  { id: "kroc-mcdonalds", person: "Ray Kroc", short: "Ray Kroc", p: "he", age: 52, event: "opened his first McDonald's franchise", year: 1955, mode: "heal", category: "food", future: "open his first McDonald's" },
  { id: "morrison-bluesteye", person: "Toni Morrison", short: "Toni Morrison", p: "she", age: 39, event: "published her first novel", year: 1970, mode: "heal", category: "literature", future: "publish her first novel" },
  { id: "morrison-nobel", person: "Toni Morrison", short: "Toni Morrison", p: "she", age: 62, event: "won the Nobel Prize in Literature", year: 1993, mode: "heal", category: "literature" },
  { id: "kant-critique", person: "Immanuel Kant", short: "Kant", p: "he", age: 57, event: "published the Critique of Pure Reason", year: 1781, mode: "heal", category: "philosophy", future: "publish the book that made him Kant" },
  { id: "ando-ramen", person: "Momofuku Ando", short: "Momofuku Ando", p: "he", age: 48, event: "invented instant noodles", year: 1958, mode: "heal", category: "food", future: "invent instant noodles" },
  { id: "ando-cupnoodles", person: "Momofuku Ando", short: "Momofuku Ando", p: "he", age: 61, event: "invented Cup Noodles", year: 1971, mode: "heal", category: "food" },
  { id: "stanlee-ff", person: "Stan Lee", short: "Stan Lee", p: "he", age: 38, event: "created the Fantastic Four", year: 1961, mode: "heal", category: "art", future: "create his first famous superheroes" },
  { id: "stanlee-spiderman", person: "Stan Lee", short: "Stan Lee", p: "he", age: 39, event: "co-created Spider-Man", year: 1962, mode: "heal", category: "art" },
  { id: "sljackson-pulp", person: "Samuel L. Jackson", short: "Samuel L. Jackson", p: "he", age: 45, event: "starred in Pulp Fiction", year: 1994, mode: "heal", category: "film" },
  { id: "freeman-daisy", person: "Morgan Freeman", short: "Morgan Freeman", p: "he", age: 52, event: "became a star with Driving Miss Daisy", year: 1989, mode: "heal", category: "film", future: "become a household name" },
  { id: "rickman-diehard", person: "Alan Rickman", short: "Alan Rickman", p: "he", age: 42, event: "made his film debut, in Die Hard", year: 1988, mode: "heal", category: "film", future: "appear in his first film" },
  { id: "cranston-heisenberg", person: "Bryan Cranston", short: "Bryan Cranston", p: "he", age: 51, event: "became Walter White", year: 2008, mode: "heal", category: "film", future: "meet Walter White" },
  { id: "carell-office", person: "Steve Carell", short: "Steve Carell", p: "he", age: 42, event: "landed The Office", year: 2005, mode: "heal", category: "film" },
  { id: "waltz-basterds", person: "Christoph Waltz", short: "Christoph Waltz", p: "he", age: 52, event: "got his international breakthrough", year: 2009, mode: "heal", category: "film" },
  { id: "hford-starwars", person: "Harrison Ford", short: "Harrison Ford", p: "he", age: 34, event: "quit carpentry when Star Wars made him a star", year: 1977, mode: "heal", category: "film", future: "quit his carpentry side job" },
  { id: "bigelow-oscar", person: "Kathryn Bigelow", short: "Kathryn Bigelow", p: "she", age: 58, event: "became the first woman to win the Best Director Oscar", year: 2010, mode: "heal", category: "film" },
  { id: "hitchcock-psycho", person: "Alfred Hitchcock", short: "Hitchcock", p: "he", age: 60, event: "made Psycho", year: 1960, mode: "heal", category: "film", future: "shoot Psycho" },
  { id: "anglee-debut", person: "Ang Lee", short: "Ang Lee", p: "he", age: 37, event: "directed his first feature film", year: 1991, mode: "heal", category: "film", future: "direct his first film" },
  { id: "rscott-alien", person: "Ridley Scott", short: "Ridley Scott", p: "he", age: 41, event: "directed Alien", year: 1979, mode: "heal", category: "film" },
  { id: "dench-oscar", person: "Judi Dench", short: "Judi Dench", p: "she", age: 64, event: "won her first Oscar", year: 1999, mode: "heal", category: "film" },
  { id: "hopkins-oscar", person: "Anthony Hopkins", short: "Anthony Hopkins", p: "he", age: 83, event: "became the oldest Best Actor winner ever", year: 2021, mode: "heal", category: "film" },
  { id: "bukowski-postoffice", person: "Charles Bukowski", short: "Bukowski", p: "he", age: 50, event: "published his first novel", year: 1971, mode: "heal", category: "literature", future: "publish his first novel" },
  { id: "mccourt-angelas", person: "Frank McCourt", short: "Frank McCourt", p: "he", age: 66, event: "published Angela's Ashes, his first book", year: 1996, mode: "heal", category: "literature", future: "publish his first book" },
  { id: "wilder-littlehouse", person: "Laura Ingalls Wilder", short: "Laura Ingalls Wilder", p: "she", age: 65, event: "published her first Little House book", year: 1932, mode: "heal", category: "literature", future: "publish her first book" },
  { id: "chandler-bigsleep", person: "Raymond Chandler", short: "Raymond Chandler", p: "he", age: 50, event: "published The Big Sleep, his first novel", year: 1939, mode: "heal", category: "literature" },
  { id: "adams-watership", person: "Richard Adams", short: "Richard Adams", p: "he", age: 52, event: "published Watership Down, his first novel", year: 1972, mode: "heal", category: "literature" },
  { id: "rowling-potter", person: "J. K. Rowling", short: "J. K. Rowling", p: "she", age: 31, event: "published the first Harry Potter, after twelve rejections", year: 1997, mode: "heal", category: "literature" },
  { id: "tolkien-hobbit", person: "J. R. R. Tolkien", short: "Tolkien", p: "he", age: 45, event: "published The Hobbit", year: 1937, mode: "heal", category: "literature" },
  { id: "tolkien-lotr", person: "J. R. R. Tolkien", short: "Tolkien", p: "he", age: 62, event: "published The Lord of the Rings", year: 1954, mode: "heal", category: "literature" },
  { id: "eliot-adambede", person: "George Eliot", short: "George Eliot", p: "she", age: 39, event: "published her first novel", year: 1859, mode: "heal", category: "literature" },
  { id: "twain-huckfinn", person: "Mark Twain", short: "Mark Twain", p: "he", age: 49, event: "published Adventures of Huckleberry Finn", year: 1885, mode: "heal", category: "literature" },
  { id: "cervantes-quixote", person: "Miguel de Cervantes", short: "Cervantes", p: "he", age: 57, event: "published Don Quixote", year: 1605, mode: "heal", category: "literature", future: "publish Don Quixote" },
  { id: "defoe-crusoe", person: "Daniel Defoe", short: "Defoe", p: "he", age: 59, event: "published Robinson Crusoe, his first novel", year: 1719, mode: "heal", category: "literature" },
  { id: "roget-thesaurus", person: "Peter Mark Roget", short: "Roget", p: "he", age: 73, event: "published his thesaurus", year: 1852, mode: "heal", category: "literature", future: "publish the thesaurus" },
  { id: "webster-dictionary", person: "Noah Webster", short: "Noah Webster", p: "he", age: 69, event: "published his American dictionary", year: 1828, mode: "heal", category: "literature" },
  { id: "sewell-blackbeauty", person: "Anna Sewell", short: "Anna Sewell", p: "she", age: 57, event: "published Black Beauty, her only novel", year: 1877, mode: "heal", category: "literature" },
  { id: "doerr-ibarra", person: "Harriet Doerr", short: "Harriet Doerr", p: "she", age: 73, event: "published her first novel", year: 1984, mode: "heal", category: "literature" },
  { id: "maclean-river", person: "Norman Maclean", short: "Norman Maclean", p: "he", age: 73, event: "published A River Runs Through It, his first book", year: 1976, mode: "heal", category: "literature" },
  { id: "stevens-harmonium", person: "Wallace Stevens", short: "Wallace Stevens", p: "he", age: 43, event: "published his first book of poems", year: 1923, mode: "heal", category: "literature" },
  { id: "golding-flies", person: "William Golding", short: "William Golding", p: "he", age: 42, event: "published Lord of the Flies, after some twenty rejections", year: 1954, mode: "heal", category: "literature" },
  { id: "stoker-dracula", person: "Bram Stoker", short: "Bram Stoker", p: "he", age: 49, event: "published Dracula", year: 1897, mode: "heal", category: "literature" },
  { id: "austen-published", person: "Jane Austen", short: "Jane Austen", p: "she", age: 35, event: "published her first novel", year: 1811, mode: "heal", category: "literature" },
  { id: "darwin-origin", person: "Charles Darwin", short: "Darwin", p: "he", age: 50, event: "published On the Origin of Species", year: 1859, mode: "heal", category: "science" },
  { id: "rousseau-salon", person: "Henri Rousseau", short: "Henri Rousseau", p: "he", age: 42, event: "exhibited his paintings for the first time", year: 1886, mode: "heal", category: "art" },
  { id: "cezanne-solo", person: "Paul Cézanne", short: "Cézanne", p: "he", age: 56, event: "got his first solo exhibition", year: 1895, mode: "heal", category: "art" },
  { id: "vangogh-painter", person: "Vincent van Gogh", short: "Van Gogh", p: "he", age: 27, event: "decided to become a painter", year: 1880, mode: "heal", category: "art", future: "pick up painting" },
  { id: "bourgeois-moma", person: "Louise Bourgeois", short: "Louise Bourgeois", p: "she", age: 70, event: "got her MoMA retrospective, the museum's first for a woman", year: 1982, mode: "heal", category: "art" },
  { id: "hokusai-wave", person: "Hokusai", short: "Hokusai", p: "he", age: 70, event: "published The Great Wave", year: 1831, mode: "heal", category: "art", future: "print The Great Wave" },
  { id: "verdi-falstaff", person: "Giuseppe Verdi", short: "Verdi", p: "he", age: 79, event: "premiered Falstaff", year: 1893, mode: "heal", category: "music", future: "premiere his final masterpiece" },
  { id: "beethoven-ninth", person: "Ludwig van Beethoven", short: "Beethoven", p: "he", age: 53, event: "premiered the Ninth Symphony, completely deaf", year: 1824, mode: "heal", category: "music" },
  { id: "cohen-album", person: "Leonard Cohen", short: "Leonard Cohen", p: "he", age: 33, event: "released his first album", year: 1967, mode: "heal", category: "music", future: "release his first album" },
  { id: "bocelli-album", person: "Andrea Bocelli", short: "Andrea Bocelli", p: "he", age: 35, event: "released his debut album", year: 1994, mode: "heal", category: "music" },
  { id: "sia-chandelier", person: "Sia", short: "Sia", p: "she", age: 38, event: "went to No. 1 worldwide with “Chandelier”", year: 2014, mode: "heal", category: "music" },
  { id: "boyle-bgt", person: "Susan Boyle", short: "Susan Boyle", p: "she", age: 47, event: "silenced a smirking audience on Britain's Got Talent", year: 2009, mode: "heal", category: "music" },
  { id: "walton-walmart", person: "Sam Walton", short: "Sam Walton", p: "he", age: 44, event: "opened the first Walmart", year: 1962, mode: "heal", category: "business", future: "open his first Walmart" },
  { id: "flint-ibm", person: "Charles Flint", short: "Charles Flint", p: "he", age: 61, event: "founded the company that became IBM", year: 1911, mode: "heal", category: "business" },
  { id: "marcus-homedepot", person: "Bernie Marcus", short: "Bernie Marcus", p: "he", age: 50, event: "co-founded Home Depot, the year after being fired", year: 1979, mode: "heal", category: "business" },
  { id: "huffington-huffpost", person: "Arianna Huffington", short: "Arianna Huffington", p: "she", age: 54, event: "launched the Huffington Post", year: 2005, mode: "heal", category: "business" },
  { id: "henryford-company", person: "Henry Ford", short: "Henry Ford", p: "he", age: 39, event: "founded the Ford Motor Company", year: 1903, mode: "heal", category: "business" },
  { id: "henryford-modelt", person: "Henry Ford", short: "Henry Ford", p: "he", age: 45, event: "launched the Model T", year: 1908, mode: "heal", category: "business" },
  { id: "honda-motor", person: "Soichiro Honda", short: "Soichiro Honda", p: "he", age: 41, event: "founded Honda", year: 1948, mode: "heal", category: "business", future: "found Honda" },
  { id: "porsche-company", person: "Ferdinand Porsche", short: "Ferdinand Porsche", p: "he", age: 55, event: "founded Porsche", year: 1931, mode: "heal", category: "business" },
  { id: "ferrari-firstcar", person: "Enzo Ferrari", short: "Enzo Ferrari", p: "he", age: 49, event: "built the first car bearing his name", year: 1947, mode: "heal", category: "business", future: "build a car with his name on it" },
  { id: "lauder-company", person: "Estée Lauder", short: "Estée Lauder", p: "she", age: 38, event: "co-founded her cosmetics company", year: 1946, mode: "heal", category: "business" },
  { id: "ortega-zara", person: "Amancio Ortega", short: "Amancio Ortega", p: "he", age: 39, event: "opened the first Zara", year: 1975, mode: "heal", category: "fashion" },
  { id: "pemberton-cocacola", person: "John Pemberton", short: "John Pemberton", p: "he", age: 54, event: "invented Coca-Cola", year: 1886, mode: "heal", category: "food", future: "mix the first Coca-Cola" },
  { id: "hershey-factory", person: "Milton Hershey", short: "Milton Hershey", p: "he", age: 45, event: "broke ground on his chocolate factory, after two failed candy companies", year: 1903, mode: "heal", category: "food" },
  { id: "hines-guide", person: "Duncan Hines", short: "Duncan Hines", p: "he", age: 55, event: "published his first restaurant guide", year: 1935, mode: "heal", category: "food" },
  { id: "handler-barbie", person: "Ruth Handler", short: "Ruth Handler", p: "she", age: 42, event: "invented Barbie", year: 1959, mode: "heal", category: "business", future: "invent Barbie" },
  { id: "buffett-fortune", person: "Warren Buffett", short: "Warren Buffett", p: "he", age: 50, event: "had made barely 1% of his eventual fortune", year: 1980, mode: "heal", category: "business" },
  { id: "mandela-president", person: "Nelson Mandela", short: "Mandela", p: "he", age: 75, event: "became president of South Africa", year: 1994, mode: "heal", category: "politics", future: "be sworn in as president" },
  { id: "churchill-pm", person: "Winston Churchill", short: "Churchill", p: "he", age: 65, event: "became prime minister", year: 1940, mode: "heal", category: "politics", future: "get the job he's remembered for" },
  { id: "churchill-nobel", person: "Winston Churchill", short: "Churchill", p: "he", age: 78, event: "won the Nobel Prize in Literature", year: 1953, mode: "heal", category: "literature" },
  { id: "gandhi-saltmarch", person: "Mahatma Gandhi", short: "Gandhi", p: "he", age: 60, event: "led the Salt March", year: 1930, mode: "heal", category: "politics" },
  { id: "meir-pm", person: "Golda Meir", short: "Golda Meir", p: "she", age: 70, event: "became prime minister of Israel", year: 1969, mode: "heal", category: "politics" },
  { id: "reagan-president", person: "Ronald Reagan", short: "Ronald Reagan", p: "he", age: 69, event: "was elected president", year: 1980, mode: "heal", category: "politics" },
  { id: "rbg-court", person: "Ruth Bader Ginsburg", short: "Ruth Bader Ginsburg", p: "she", age: 60, event: "joined the US Supreme Court", year: 1993, mode: "heal", category: "politics" },
  { id: "teresa-charity", person: "Mother Teresa", short: "Mother Teresa", p: "she", age: 40, event: "founded the Missionaries of Charity", year: 1950, mode: "heal", category: "life" },
  { id: "mcclintock-nobel", person: "Barbara McClintock", short: "Barbara McClintock", p: "she", age: 81, event: "won the Nobel Prize", year: 1983, mode: "heal", category: "science" },
  { id: "goodenough-battery", person: "John B. Goodenough", short: "John Goodenough", p: "he", age: 57, event: "co-created the lithium-ion battery", year: 1980, mode: "heal", category: "science" },
  { id: "goodenough-nobel", person: "John B. Goodenough", short: "John Goodenough", p: "he", age: 97, event: "won the Nobel Prize, the oldest laureate in history", year: 2019, mode: "heal", category: "science" },
  { id: "copernicus-revolutions", person: "Nicolaus Copernicus", short: "Copernicus", p: "he", age: 70, event: "published the book that moved the Earth", year: 1543, mode: "heal", category: "science", future: "publish his heliocentric theory" },
  { id: "franklin-declaration", person: "Benjamin Franklin", short: "Ben Franklin", p: "he", age: 70, event: "signed the Declaration of Independence", year: 1776, mode: "heal", category: "politics" },
  { id: "fleming-penicillin", person: "Alexander Fleming", short: "Fleming", p: "he", age: 47, event: "discovered penicillin", year: 1928, mode: "heal", category: "science", future: "notice that famous mold" },
  { id: "michelangelo-stpeters", person: "Michelangelo", short: "Michelangelo", p: "he", age: 71, event: "became chief architect of St. Peter's Basilica", year: 1547, mode: "heal", category: "art" },
  { id: "nyad-swim", person: "Diana Nyad", short: "Diana Nyad", p: "she", age: 64, event: "swam from Cuba to Florida", year: 2013, mode: "heal", category: "sports", future: "make it from Cuba to Florida" },
  { id: "miura-everest", person: "Yuichiro Miura", short: "Yuichiro Miura", p: "he", age: 80, event: "stood on the summit of Everest", year: 2013, mode: "heal", category: "exploration", future: "summit Everest" },
  { id: "whitlock-marathon", person: "Ed Whitlock", short: "Ed Whitlock", p: "he", age: 72, event: "ran a marathon in under three hours", year: 2003, mode: "heal", category: "sports" },
  { id: "swahn-medal", person: "Oscar Swahn", short: "Oscar Swahn", p: "he", age: 72, event: "won an Olympic medal, still the oldest medalist ever", year: 1920, mode: "heal", category: "sports" },
  { id: "bhillary-northpole", person: "Barbara Hillary", short: "Barbara Hillary", p: "she", age: 75, event: "reached the North Pole", year: 2007, mode: "heal", category: "exploration" },
  { id: "glenn-shuttle", person: "John Glenn", short: "John Glenn", p: "he", age: 77, event: "flew on the Space Shuttle", year: 1998, mode: "heal", category: "exploration", future: "go back to space" },
  { id: "funk-space", person: "Wally Funk", short: "Wally Funk", p: "she", age: 82, event: "finally reached space", year: 2021, mode: "heal", category: "exploration", future: "get her ride to space" },
  { id: "shatner-space", person: "William Shatner", short: "William Shatner", p: "he", age: 90, event: "flew to space, the oldest human ever to do so", year: 2021, mode: "heal", category: "exploration" },
  { id: "maruge-school", person: "Kimani Maruge", short: "Kimani Maruge", p: "he", age: 84, event: "enrolled in primary school", year: 2004, mode: "heal", category: "life", future: "start first grade" },
  { id: "ochs-degree", person: "Nola Ochs", short: "Nola Ochs", p: "she", age: 95, event: "graduated from college", year: 2007, mode: "heal", category: "life", future: "collect her diploma" },
  { id: "wakamiya-app", person: "Masako Wakamiya", short: "Masako Wakamiya", p: "she", age: 81, event: "shipped her first iPhone app", year: 2017, mode: "heal", category: "tech", future: "ship her first app" },
  { id: "shepherd-training", person: "Ernestine Shepherd", short: "Ernestine Shepherd", p: "she", age: 56, event: "started the training that made her the world's oldest competitive bodybuilder", year: 1992, mode: "heal", category: "sports" },
  { id: "burrill-marathon", person: "Gladys Burrill", short: "Gladys Burrill", p: "she", age: 92, event: "completed the Honolulu Marathon", year: 2010, mode: "heal", category: "sports" }
];

// Canonical domain — change here and in build.js BASE_URL when the real domain exists.
const AYA_DOMAIN = "atyourage.fyi";

if (typeof module !== "undefined" && module.exports) {
  module.exports = { MILESTONES: AYA_MILESTONES, DOMAIN: AYA_DOMAIN };
}
